input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [type] == "python-json" {
    mutate {
      remove_field => [ "host" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "petro-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
